// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBM-R1sTcAssd6t0DTy3HZygogVQUxznOM',
    appId: '1:236188595426:web:9933be0038542f29699abb',
    messagingSenderId: '236188595426',
    projectId: 'coding-tutor-42184',
    authDomain: 'coding-tutor-42184.firebaseapp.com',
    storageBucket: 'coding-tutor-42184.firebasestorage.app',
    measurementId: 'G-907TMRBFH4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdZRe06GPB81GFJ5fnbDhgJQt2nV8FJeU',
    appId: '1:236188595426:android:a94d086f0a35fa14699abb',
    messagingSenderId: '236188595426',
    projectId: 'coding-tutor-42184',
    storageBucket: 'coding-tutor-42184.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNVe_QOfUDFwx_nD2PBsrcN7PkVmVic3o',
    appId: '1:236188595426:ios:4e9406c371900841699abb',
    messagingSenderId: '236188595426',
    projectId: 'coding-tutor-42184',
    storageBucket: 'coding-tutor-42184.firebasestorage.app',
    iosBundleId: 'com.example.codingTutor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNVe_QOfUDFwx_nD2PBsrcN7PkVmVic3o',
    appId: '1:236188595426:ios:4e9406c371900841699abb',
    messagingSenderId: '236188595426',
    projectId: 'coding-tutor-42184',
    storageBucket: 'coding-tutor-42184.firebasestorage.app',
    iosBundleId: 'com.example.codingTutor',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBM-R1sTcAssd6t0DTy3HZygogVQUxznOM',
    appId: '1:236188595426:web:959616fe1a593317699abb',
    messagingSenderId: '236188595426',
    projectId: 'coding-tutor-42184',
    authDomain: 'coding-tutor-42184.firebaseapp.com',
    storageBucket: 'coding-tutor-42184.firebasestorage.app',
    measurementId: 'G-BNGTPR4VG9',
  );

}